import LegalLayout, { Section } from "./LegalLayout";
import { LEGAL, SUBPROCESSORS } from "@/lib/legal";

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      title="Privacy Policy"
      intro={`This explains what ${LEGAL.entity} collects, why, and who else sees it. It describes what the app actually does today, not what it might do later.`}
    >
      <Section heading="What we collect">
        <p>
          <strong>Your account.</strong> When you sign in with Google we receive your email
          address, your name and your profile picture. We never see or store your Google
          password.
        </p>
        <p>
          <strong>Your birth details.</strong> Your date of birth, time of birth and place of
          birth, including the latitude and longitude of that place. These are the inputs an
          astrological chart is computed from — without them the app cannot do its job.
        </p>
        <p>
          <strong>What you write.</strong> The questions you put to the Guru, the dreams you
          submit for interpretation, and any names you give to charts you create for other
          people.
        </p>
        <p>
          <strong>How you use the app.</strong> Which readings you generate and when, your
          language preference, and whether you have marked a ritual as done. We use this to
          keep your place and to apply the limits of your plan.
        </p>
      </Section>

      <Section heading="Birth details deserve a word of their own">
        <p>
          A birth date, an exact birth time and a birthplace together identify a person quite
          precisely. Treat them as you would any sensitive personal record. We store them so
          that your chart does not have to be re-entered every time, and we do not sell them,
          rent them, or use them for advertising.
        </p>
        <p>
          If you enter birth details for somebody else — a partner for a compatibility reading,
          a family member — you are responsible for having their agreement to do so.
        </p>
      </Section>

      <Section heading="Readings are generated by an AI model">
        <p>
          The written readings are not pre-written text. When you request one, the relevant
          computed parts of your chart, and anything you have typed into the Guru or the Dream
          Oracle, are sent to Anthropic's API, which returns the text you read.
        </p>
        <p>
          This means the content of your questions and dreams leaves our systems. Please do not
          type anything into the app that you would not want processed by a third-party AI
          service — in particular, no financial account details, passwords, or identity
          document numbers.
        </p>
      </Section>

      <Section heading="Who else sees your data">
        <p>We use a small number of service providers. Each one is listed here with what it is for:</p>
        <ul className="space-y-2 pl-4 list-disc marker:text-[hsl(var(--gold))]">
          {SUBPROCESSORS.map((s) => (
            <li key={s.name}>
              <strong>{s.name}.</strong> {s.purpose}
            </li>
          ))}
        </ul>
        <p>
          We do not sell your personal information, and we do not share it with advertisers.
        </p>
      </Section>

      <Section heading="How long we keep it">
        <p>
          Your account and birth details are kept for as long as your account exists. Generated
          readings are cached so that opening the same reading twice does not regenerate and
          recharge it; these expire on their own over time.
        </p>
        <p>
          If you ask us to delete your account, we delete your profile, your charts, your
          readings and the things you have written. Backups may retain copies for a short
          period before they roll over.
        </p>
      </Section>

      <Section heading="What you can ask us to do">
        <p>
          You can ask for a copy of what we hold about you, ask us to correct it, or ask us to
          delete it and close your account. You can change your birth details and your name
          yourself at any time from your profile.
        </p>
        <p>
          Depending on where you live, you may have further rights under local data protection
          law, including the right to complain to a supervisory authority.
        </p>
      </Section>

      <Section heading="Children">
        <p>
          This service is not intended for children under 13, and we do not knowingly collect
          their information. If you believe a child has given us their details, write to us and
          we will remove them.
        </p>
      </Section>

      <Section heading="Changes">
        <p>
          If this policy changes in a way that affects you, we will update the date at the top
          and, for significant changes, tell you in the app.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Write to <a href={`mailto:${LEGAL.contactEmail}`} style={{ color: "hsl(var(--gold))" }}>{LEGAL.contactEmail}</a>{" "}
          with any question about this policy, or to make any of the requests described above.
        </p>
      </Section>
    </LegalLayout>
  );
}
