import LegalLayout, { Section } from "./LegalLayout";
import { LEGAL } from "@/lib/legal";

export default function TermsOfService() {
  return (
    <LegalLayout
      title="Terms of Service"
      intro={`These are the terms you agree to by using ${LEGAL.entity}. They are written to be read, not to be impenetrable.`}
    >
      <Section heading="What this service is">
        <p>
          {LEGAL.entity} computes Vedic astrological charts from the birth details you provide
          and generates written readings from them, along with related features: daily
          horoscopes, compatibility analysis, dream interpretation, remedies and muhurta
          timings.
        </p>
      </Section>

      <Section heading="What it is not">
        <p>
          <strong>
            Readings are for reflection and entertainment. They are not professional advice.
          </strong>{" "}
          Nothing here is medical, psychological, legal, financial or relationship advice, and
          nothing here should replace a qualified professional.
        </p>
        <p>
          Do not make a medical decision, a financial commitment, or a decision about your
          safety or another person's on the basis of a reading. If you are struggling with your
          health or your state of mind, speak to a doctor or a crisis service in your country.
        </p>
        <p>
          The readings are produced by an AI model working from classical rules. They can be
          wrong, inconsistent between runs, or simply unhelpful. Treat them as one voice, not
          as fact.
        </p>
      </Section>

      <Section heading="Your account">
        <p>
          You sign in with Google. You are responsible for the security of that Google account,
          and for everything done through your session. You must be old enough to form a
          binding agreement where you live, and at least 13 in any case.
        </p>
        <p>
          Give accurate birth details if you want meaningful output — an approximate birth time
          produces an approximate chart, and that is a limitation of the method, not a fault.
        </p>
      </Section>

      <Section heading="Using it fairly">
        <p>You agree not to:</p>
        <ul className="space-y-2 pl-4 list-disc marker:text-[hsl(var(--gold))]">
          <li>resell, scrape or bulk-extract readings, or use the service to run a competing one;</li>
          <li>submit another living person's birth details without their agreement;</li>
          <li>attempt to break, overload or work around the limits of your plan;</li>
          <li>use the service to harass, frighten or deceive anybody, including by presenting a reading as a prediction of someone's death, illness or misfortune.</li>
        </ul>
      </Section>

      <Section heading="Plans and payment">
        <p>
          Some features belong to paid plans. Prices are shown on the pricing page before you
          commit to anything.
        </p>
        <p>
          <strong>Payments are not open yet.</strong> Until they are, no charge can be made and
          no payment details are collected. When paid plans do open, the terms covering
          billing, renewal, cancellation and refunds will be set out here before any money
          changes hands.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          We try to keep the service running, but we do not promise it will be uninterrupted.
          Features may change or be withdrawn. Generated readings depend on a third-party AI
          service and can fail or be delayed for reasons outside our control.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          To the extent the law allows, {LEGAL.entity} is not liable for any loss arising from
          decisions you make on the basis of a reading, from an interruption to the service, or
          from content generated by the AI model.
        </p>
        <p>
          Nothing in these terms removes any right you have under consumer law that cannot be
          removed by agreement.
        </p>
      </Section>

      <Section heading="Ending it">
        <p>
          You can stop using the service and ask for your account to be deleted at any time. We
          may suspend or close an account that breaks these terms.
        </p>
      </Section>

      <Section heading="Governing law">
        <p>
          These terms are governed by the law of {LEGAL.governingLaw}, without regard to its
          conflict-of-law rules.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Write to <a href={`mailto:${LEGAL.contactEmail}`} style={{ color: "hsl(var(--gold))" }}>{LEGAL.contactEmail}</a>.
        </p>
      </Section>
    </LegalLayout>
  );
}
