-- The remedies table has been empty since it was created (20260222004154):
-- nothing ever inserted into it, so the Remedy Library tab — the whole free
-- tier of /remedies — showed "No remedies found" to every user while only the
-- premium Prescription view (generated by generate-remedies) had content.
--
-- Seeds the nine grahas across the four categories the page filters on
-- (mantra, gemstone, ritual, general). Category values are lowercase to match
-- the t("pages:ui.remediesPage.cat_" + category) lookup, and planet values stay
-- raw English because the page uses them as filter values and as keys into
-- PLANET_EMOJI and planetLabel().
--
-- Guarded on the table being empty: admins manage this table through the admin
-- Remedies page, so a re-run must never duplicate rows or overwrite their edits.

insert into public.remedies (title, category, planet, description, mantra, gemstone, ritual)
select v.title, v.category, v.planet, v.description, v.mantra, v.gemstone, v.ritual
from (values
  -- ── Sun (Surya) ──────────────────────────────────────────────────────────
  ('Surya Beej Mantra', 'mantra', 'Sun',
   'For a weak, combust or afflicted Sun. Steadies confidence, standing with authority, and the relationship with the father. Begin on a Sunday at sunrise and keep the count the same each day.',
   'Om Hraam Hreem Hraum Sah Suryaya Namah — 7,000 repetitions to complete the anushthana, one mala (108) daily at sunrise.', null, null),
  ('Ruby for the Sun', 'gemstone', 'Sun',
   'Manikya strengthens a Sun that is weak by placement rather than one already strong — a well-placed Sun rarely needs it. Have the chart read before you buy.',
   null, 'Ruby (Manikya), 3–6 carats, set in gold or copper, worn on the ring finger of the right hand. First worn on a Sunday at sunrise.', null),
  ('Surya Arghya at Sunrise', 'ritual', 'Sun',
   'The simplest daily Sun remedy and the one most often prescribed, because it costs nothing and asks only that you rise early.',
   null, null, 'Face the rising sun and offer water from a copper vessel, letting it fall through the light. Add a pinch of red sandalwood. Do this daily for forty days.'),

  -- ── Moon (Chandra) ───────────────────────────────────────────────────────
  ('Chandra Beej Mantra', 'mantra', 'Moon',
   'For an afflicted or waning Moon — restlessness, broken sleep, a mind that will not settle, strain with the mother.',
   'Om Shraam Shreem Shraum Sah Chandraya Namah — 11,000 repetitions, recited in the evening.', null, null),
  ('Pearl for the Moon', 'gemstone', 'Moon',
   'Moti cools and steadies the emotional mind. Among the gentlest of the nine stones, and the one least likely to overcorrect.',
   null, 'Natural pearl (Moti), 4–7 carats, set in silver, worn on the little finger of the right hand. First worn on a Monday evening.', null),
  ('Monday Vrata and Milk Offering', 'ritual', 'Moon',
   'Observed for peace of mind and for the mother''s wellbeing. Traditionally kept through a full waxing fortnight.',
   null, null, 'Fast on Mondays taking only milk and white foods, and offer milk over a Shiva lingam in the evening. Keep white rice or white cloth for donation.'),

  -- ── Mars (Mangal) ────────────────────────────────────────────────────────
  ('Mangal Beej Mantra', 'mantra', 'Mars',
   'For an afflicted Mars — a temper that arrives before the thought, accidents, disputes, or a stalled Mangal dosha matter.',
   'Om Kraam Kreem Kraum Sah Bhaumaya Namah — 10,000 repetitions, begun on a Tuesday.', null, null),
  ('Red Coral for Mars', 'gemstone', 'Mars',
   'Moonga lends courage and physical vitality to a weak Mars. Not worn when Mars is already strong or badly placed for your lagna — it sharpens what is there.',
   null, 'Red Coral (Moonga), 6–9 carats, set in copper or gold, worn on the ring finger of the right hand. First worn on a Tuesday at sunrise.', null),
  ('Tuesday Hanuman Sadhana', 'ritual', 'Mars',
   'The standard remedy for Mars affliction and for Mangal dosha, and the one prescribed most freely because it carries no risk.',
   null, null, 'Recite the Hanuman Chalisa on Tuesday, offer red flowers and jaggery, and keep a fast from sunrise until the evening lamp.'),

  -- ── Mercury (Budha) ──────────────────────────────────────────────────────
  ('Budha Beej Mantra', 'mantra', 'Mercury',
   'For an afflicted Mercury — scattered speech, faltering memory, trouble in study, contracts and commerce.',
   'Om Braam Breem Braum Sah Budhaya Namah — 9,000 repetitions, begun on a Wednesday.', null, null),
  ('Emerald for Mercury', 'gemstone', 'Mercury',
   'Panna sharpens intellect, speech and commercial judgement when Mercury is weak. Favoured for students and for those who live by negotiation.',
   null, 'Emerald (Panna), 3–6 carats, set in gold, worn on the little finger of the right hand. First worn on a Wednesday at sunrise.', null),
  ('Wednesday Green Daan', 'ritual', 'Mercury',
   'Mercury is settled by charity in its own colour, given on its own day, without announcement.',
   null, null, 'On Wednesday give green moong dal, green cloth or fodder to cows, and feed green vegetables to a calf. Keep it unremarked.'),

  -- ── Jupiter (Guru / Brihaspati) ──────────────────────────────────────────
  ('Guru Beej Mantra', 'mantra', 'Jupiter',
   'For a weak or afflicted Jupiter — blocked growth, absent guidance, difficulty with teachers, children or marriage for a woman.',
   'Om Graam Greem Graum Sah Gurave Namah — 19,000 repetitions, begun on a Thursday.', null, null),
  ('Yellow Sapphire for Jupiter', 'gemstone', 'Jupiter',
   'Pukhraj is the most widely prescribed of the nine stones and the most forgiving, but it still belongs to a chart where Jupiter is weak rather than merely disliked.',
   null, 'Yellow Sapphire (Pukhraj), 5–8 carats, set in gold, worn on the index finger of the right hand. First worn on a Thursday at sunrise.', null),
  ('Thursday Vrata and Turmeric Daan', 'ritual', 'Jupiter',
   'Kept for wisdom, for a teacher''s blessing, and traditionally by women seeking marriage.',
   null, null, 'Fast on Thursday taking yellow food once, wear something yellow, and donate turmeric, chana dal or yellow cloth to a teacher or a temple.'),

  -- ── Venus (Shukra) ───────────────────────────────────────────────────────
  ('Shukra Beej Mantra', 'mantra', 'Venus',
   'For an afflicted Venus — discord in marriage and partnership, blocked creative work, an unsteady sense of comfort and beauty.',
   'Om Draam Dreem Draum Sah Shukraya Namah — 16,000 repetitions, begun on a Friday.', null, null),
  ('Diamond for Venus', 'gemstone', 'Venus',
   'Heera strengthens Venus in relationship, artistry and material ease. White sapphire is the accepted substitute and is often the wiser first choice.',
   null, 'Diamond (Heera) or White Sapphire as substitute, 1–2 carats for diamond, set in silver or platinum, worn on the middle finger. First worn on a Friday at sunrise.', null),
  ('Friday White Offering', 'ritual', 'Venus',
   'Venus is settled through beauty freely given rather than acquired.',
   null, null, 'On Friday offer white sweets, curd or white flowers, donate white cloth or perfume to a woman, and keep the day free of argument.'),

  -- ── Saturn (Shani) ───────────────────────────────────────────────────────
  ('Shani Beej Mantra', 'mantra', 'Saturn',
   'For Sade Sati, a Shani dasha, or an afflicted Saturn — delay, heaviness, chronic obstruction, work that never quite concludes.',
   'Om Praam Preem Praum Sah Shanaischaraya Namah — 23,000 repetitions, the longest of the nine anushthanas. Begun on a Saturday.', null, null),
  ('Blue Sapphire for Saturn', 'gemstone', 'Saturn',
   'Neelam acts faster than any other stone and is the one most often prescribed wrongly. It is never worn on the strength of a Saturn period alone — only after the chart is read, and only after it has been tested.',
   null, 'Blue Sapphire (Neelam), 3–5 carats, set in silver or iron, worn on the middle finger of the right hand. Test-wear it for three nights before energizing: if sleep, health or circumstance worsens, return it.', null),
  ('Saturday Oil Lamp and Service', 'ritual', 'Saturn',
   'Saturn is answered by service and by patience, not by appeasement. This is the remedy prescribed through Sade Sati above all others.',
   null, null, 'On Saturday light a sesame-oil lamp beneath a peepal tree at dusk, feed crows and stray dogs, and donate black sesame, iron or mustard oil to someone who labours.'),

  -- ── Rahu ─────────────────────────────────────────────────────────────────
  ('Rahu Beej Mantra', 'mantra', 'Rahu',
   'For a Rahu dasha or an afflicted Rahu — confusion, obsession, sudden reversals, fear without an object.',
   'Om Bhraam Bhreem Bhraum Sah Rahave Namah — 18,000 repetitions, recited after dusk.', null, null),
  ('Hessonite for Rahu', 'gemstone', 'Rahu',
   'Gomed steadies a scattered Rahu. Like Neelam it is quick to act, so it is tested before it is trusted.',
   null, 'Hessonite (Gomed), 6–9 carats, set in silver, worn on the middle finger of the right hand. First worn on a Saturday after dusk, following a three-night trial.', null),
  ('Rahu Daan and Durga Path', 'ritual', 'Rahu',
   'Rahu quietens when given to those it governs — the overlooked, the outcast, the unhoused.',
   null, null, 'Recite the Durga Saptashati or Durga Chalisa, feed stray dogs, and donate blankets, mustard oil or black-and-blue cloth to the destitute on Saturday.'),

  -- ── Ketu ─────────────────────────────────────────────────────────────────
  ('Ketu Beej Mantra', 'mantra', 'Ketu',
   'For a Ketu dasha or an afflicted Ketu — detachment where engagement is needed, unexplained ailments, a sense of being cut loose.',
   'Om Straam Streem Straum Sah Ketave Namah — 7,000 repetitions, begun on a Tuesday.', null, null),
  ('Cat''s Eye for Ketu', 'gemstone', 'Ketu',
   'Lehsunia is prescribed sparingly and for a well-defined Ketu affliction, never as a general strengthener.',
   null, 'Cat''s Eye (Lehsunia), 5–7 carats, set in silver, worn on the ring finger of the right hand. First worn on a Tuesday after a three-night trial.', null),
  ('Ganesha Worship and Dog Feeding', 'ritual', 'Ketu',
   'Ketu is the headless graha; it is addressed through Ganesha, who carries the head that was replaced.',
   null, null, 'Worship Ganesha on Tuesday, feed stray dogs, and donate blankets, sesame or a multicoloured cloth. Keep one day a week free of acquisition.'),

  -- ── General — not tied to one graha ───────────────────────────────────────
  ('Gayatri Mantra', 'general', null,
   'The universal remedy. Prescribed when the chart shows diffuse affliction rather than one clear culprit, and safe in every chart without exception.',
   'Om Bhur Bhuvah Svah, Tat Savitur Varenyam, Bhargo Devasya Dheemahi, Dhiyo Yo Nah Prachodayat — one mala (108) at sunrise or sunset.', null, null),
  ('Maha Mrityunjaya Mantra', 'general', null,
   'For health, recovery and protection through a difficult transit. Given when longevity factors or the eighth house are under strain.',
   'Om Tryambakam Yajamahe Sugandhim Pushtivardhanam, Urvarukamiva Bandhanan Mrityor Mukshiya Maamritat — 125,000 repetitions for a full anushthana, or one mala daily.', null, null),
  ('Daan on the Graha''s Own Day', 'general', null,
   'The underlying principle behind most planetary charity: give what the afflicted graha rules, on the weekday it rules, to someone who needs it, and do not speak of it afterwards.',
   null, null, 'Identify the afflicted graha, then give its substance on its day — wheat and jaggery on Sunday, rice and milk on Monday, lentils on Tuesday, green gram on Wednesday, turmeric on Thursday, curd on Friday, sesame and iron on Saturday.'),
  ('Annadaan — the Feeding of Others', 'general', null,
   'Held in the classical texts as the charity that answers any graha, and the one prescribed when a chart is too afflicted to isolate a single remedy.',
   null, null, 'Feed someone who cannot feed themselves — a person, a cow, a crow, a stray. Weekly, without announcement, and without choosing who deserves it.'),
  ('Sandhya — Keeping the Junctions', 'general', null,
   'Sunrise and sunset are the junctions of the day. Observing them steadies the whole chart, which is why it is asked of every practitioner before any specific remedy is given.',
   null, null, 'Sit quietly for a few minutes at sunrise and again at sunset. No mantra is required. Consistency is the remedy; forty unbroken days is the traditional measure.')
) as v(title, category, planet, description, mantra, gemstone, ritual)
-- Seed only into an empty table: never duplicate on a re-run, never overwrite
-- rows an admin has since added or edited.
where not exists (select 1 from public.remedies);
