// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE is the flow for public clients: the code that comes back in the URL
    // is worthless without the verifier held in this browser, so an intercepted
    // redirect cannot be replayed into a session.
    flowType: "pkce",
    // Let the client pick the session out of the OAuth redirect automatically.
    detectSessionInUrl: true,
  }
});